### ISSUE TITLE
多次通知以后在通知栏只显示最新一条通知

### ISSUE THREAD

**Issue by imeasyer** [ParadiseHell/mipush-cordova-plugin#1]
我在小米的官网上创建并推送了多条通知。但是每次有一条新的通知以后，之前的推送就不再显示。这是为何？

**Comment by ParadiseHell** [comment]
这个问题应该是小米推送SDK的问题，插件的功能只是通过js调用java代码，然后实现广播接受，再将接受内容传给js，显示这块是启用SDK后自动显示的，所以这个问题可以客服小米推送，看一下具体什么原因。

**Comment by ParadiseHell** [comment]
这个可能是你的  **notifyId**  一样导致的，你可以去试一试改变一下notifyId。
**http://www.miui.com/thread-3951650-1-1.html**，可以看一下这个地址的解决方案。

**Comment by ParadiseHell** [comment]
具体的服务端的代码我并没有写过，但应该也不难，notifyId写为当前时间戳就行了，但是官方的推送工具没有提供修改notifyId的方法，所以如果在官方的推送工具上是无法进行测试，得结合服务端SDK才可以测试。
